# Based on https://gitlab.com/humaid/yabfig/blob/master/.gitlab-ci.yml by Humaid
image: golang:latest

variables:
  REPO_NAME: gitlab.com/group-nacdlow/nacdlow-server
  BINARY: nacdlow-server

before_script:
  - cd $CI_PROJECT_DIR
  - go get -u github.com/go-bindata/go-bindata/...
  - go install github.com/go-bindata/go-bindata/...

stages:
    - get
    - build

compile:
    stage: build
    script:
      - make
    artifacts:
      paths:
        - $BINARY

